# Generated by Django 5.0.1 on 2024-04-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timer',
            old_name='minutes',
            new_name='work_duration',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='seconds',
        ),
        migrations.AddField(
            model_name='timer',
            name='break_duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='timer',
            name='long_break_duration',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='timer',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
